name: Swift Package Manager Verify
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify
      run: swift package dump-package
